### ISSUE TITLE
Add support for Mockito 1.10.9+

### ISSUE THREAD

**Issue by mariuszs** [Codearte/catch-exception#11]

**Comment by hazendaz** [comment]
I'd like to propose a secondary solution here and wanted some feedback.  What if we were to shade mockito 1.10.8 which would allow this library to be used with other versions of mockito.  As it stands, I'm using this library and two version so of mockito (1.10.8 and 1.10.19).  This only works because I'm doing so in separate modules within a multi module build project.  That said, I think shading might be a better approach.  I don't really see how mockito will bring much more to this library regardless of future changes.  Otherwise, if shading isn't a better solution, then why not go ahead and make a pull request on this one and hopefully owners will accept.  After much review, I think shading is better, with this being secondary.  The fact that this already is functional makes it immediately better as shading will take a little bit more time to pull off.

**Comment by evilmilo** [comment]
If the license is compatible (assuming it is), a more lightweight solution would be to copy the cglib manipulation classes out of mockito into catch-exception.  There's a lot of code in mockito not used, only a small part that is leveraged for catch-exception.

**Comment by fgaule** [comment]
Is there any plan to make it work?

**Comment by urbmic** [comment]
+1 to what @fgaule has written. We would like to upgrade to mockito 2.0 as soon as it is released this month, but that would break all our tests using catch-exception.

**Comment by mariuszs** [comment]
Yes, there is a plan. Can you test #19 with mockito 2.0 ?

**Comment by urbmic** [comment]
Thanks for info @mariuszs. Mockito 2.0 is still not released but I tried #19 together with 2.0.5-beta and it worked smoothly. Hope to see this fix in catch-exception 1.3.5.

**Comment by mkordas** [comment]
According to Szczepan's [blog post](http://blog.mockito.org/2015/01/continuously-delivering-beta-versions.html) we don't need to wait for Mockito 2.0 as beta versions have different meaning here. When can we expect 1.3.5 release?

**Comment by mariuszs** [comment]
will be relased in this week, maybe tommorow

**Comment by mariuszs** [comment]
Please try [catch-exception-1.4.1-beta-2.jar](https://oss.sonatype.org/service/local/repositories/releases/content/eu/codearte/catch-exception/catch-exception/1.4.1-beta-2/catch-exception-1.4.1-beta-2.jar)

**Comment by nprncbl** [comment]
@mariuszs 1.4.1-beta-2 works without any problems in my case - but it is still marked beta. Is there any chance to get that stable release out, either 1.3.5 or 1.4.1? I really do not care that much which one, I am only a bit hesitant to use beta-rated libraries in (testing for) production.

Thanks!

**Comment by mariuszs** [comment]
Thank for veryfing, 1.4.1 is relased.

**Comment by mkordas** [comment]
Works like a charm, thank you!

**Comment by adammichalik** [comment]
Hi! As much as I appreciate and use catch-exception a lot, since the shaded Mockito was included, it introduced some evasive problems in the tests when the incorrect class was imported. If by mistake a mix of original and shaded Mockito classes is used in the test, it will (obviously) fail and it is usually not the first idea to check your imports. Any chance of rethinking this solution?

**Comment by evilmilo** [comment]
Just restrict imports in your IDE.  You should never be using the shaded classes in your own code

**Comment by adammichalik** [comment]
Wonderful, thanks for the tip, didn't know about that option!
