### ISSUE TITLE
JaCoCo agent shouldn't be activated on every build

### ISSUE THREAD

**Issue by szpak** [Codearte/catch-exception#4]
Only on demand to not introduce performance overhead on simple "mvn test".

**Comment by hazendaz** [comment]
Solution to building this quicker.   use -T to build modules in parallel.

mvn clean install -T 2.0C

This seems to be a sweet spot.  I've got an i7 chip.  I tried higher number and got a slightly faster build but essentially at this level it builds in less than 8.5 seconds.

**Comment by szpak** [comment]
@hazendaz Good catch - in Gradle builds I have it enabled by default. Nevertheless it is only a workaround - parallel build without JaCoCo should be even faster :).

**Comment by hennr** [comment]
If jacoco is used for coveralls only, the simplest solution would be to switch to cobertura.
I use it one my project and it works fine without any overhead.

Should I open a pull request to see if coveralls behaves the same?

**Comment by hazendaz** [comment]
Really see no need.  Its seconds we are talking about.  Machine dependent of course. Plus cobertura doesn't support jdk8 fully.  It still has open issues on that.  Might not matter here though since this is really sort of eol if you will on jdk8.  Although certainly worth checking out for speed comparisons.

--- Original Message ---

**Comment by mariuszs** [comment]
Im closing this without change because branch 2.x took only 7.817 s to fully build project and there is no PR to merge :)
